object Versions {
    const val gradlePlugin = "7.4.2"
    const val kotlinPlugin = "1.8.0"
    const val activityKtx ="1.5.1"
    const val nav_version = "2.6.0-alpha07"
    const val lifecycle_version = "2.6.0"
    const val lifecycleExtVersion = "2.2.0"
    const val room_version = "2.5.1"
    const val paging_version = "3.1.1"
    const val legacy_support = "1.0.0"
    const val core_ktx = "1.9.0"
    const val appcompat = "1.6.1"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val kotlin_coroutines = "1.6.4"
    const val hilt_version = "2.45"
    const val hilt_viewModel = "1.0.0-alpha03"
    const val hilt_navigation = "1.0.0"
    const val retrofit_version = "2.9.0"
    const val moshi_version = "1.14.0"
    const val logging_interceptor = "5.0.0-alpha.3"
    const val picasso = "2.71828"
    const val junit = "4.13.2"
    const val ext_junit = "1.1.5"
    const val espresso = "3.5.1"
}